---
site_name: Runtime Error Detector
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path:
        - "../"
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - index.md
  - Getting Started: getting-started.md
  - Analyzable Java Code: valid-code.md
  - How It Works: analysis-description.md
  - Annotations:
      - annotations/index.md
      - Arrays: annotations/arrays.md
      - Numbers: annotations/numbers.md
  - Potential Errors:
      - ArithmeticException: potential-errors/ArithmeticException.md
      - ArrayIndexOutOfBoundsException: potential-errors/ArrayIndexOutOfBoundsException.md
      - ClassCastException: potential-errors/ClassCastException.md
      - NegativeArraySizeException: potential-errors/NegativeArraySizeException.md
      - NullPointerException: potential-errors/NullPointerException.md
      - Annotation Errors: potential-errors/AnnotationError.md
  - Examples:
      - Annotation: examples/annotation.md
      - Binary Search: examples/binary-search.md
