---
site_name: Runtime Error Detector
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - index.md
  - Getting Started: getting-started.md
  - Annotations:
      - Arrays: annotations/arrays.md
      - Numbers: annotations/numbers.md
  - Potential Errors:
      - ArithmeticException: potential-errors/ArithmeticException.md
      - ArrayIndexOutOfBoundsException: potential-errors/ArrayIndexOutOfBoundsException.md
      - ClassCastException: potential-errors/ClassCastException.md
      - NegativeArraySizeException: potential-errors/NegativeArraySizeException.md
      - NullPointerException: potential-errors/NullPointerException.md
